# Generated by Django 3.1.7 on 2021-07-19 12:37

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210718_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'invalid': '正しいメールアドレスを入力してください．', 'required': 'この項目は必須です．', 'unique': 'このメールアドレスは既に登録されています．'}, max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '入力いただいたユーザー名は既に存在しています．別のをお試しください．'}, help_text='必須の項目です．全角文字，半角英数字，@/./+/-/_ で50文字以下にしてください．', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
